In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([1, 2, 3])

result = np.dot(A, B)
print("Matrix-Vector Multiplication Result:")
print(result)

trace = np.trace(A)
print("\nTrace of Matrix A:")
print(trace)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of Matrix A:")
print(eigenvalues)
print("\nEigenvectors of Matrix A:")
print(eigenvectors)

Matrix-Vector Multiplication Result:
[14 32 50]

Trace of Matrix A:
15

Eigenvalues of Matrix A:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors of Matrix A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [4]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A[-1, :] = [10, 11, 12]

det_A = np.linalg.det(A)
print("Determinant of the updated matrix A:")
print(det_A)

if det_A == 0:
    print("\nThe updated matrix A is singular.")
else:
    print("\nThe updated matrix A is non-singular.")

Determinant of the updated matrix A:
0.0

The updated matrix A is singular.


In [5]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A[-1, :] = [10, 11, 12]

det_A = np.linalg.det(A)

if det_A != 0:
    print("The matrix A is invertible.")
    inv_A = np.linalg.inv(A)
    print("Inverse of Matrix A:")
    print(inv_A)
else:
    print("The matrix A is not invertible.")

The matrix A is not invertible.


In [6]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A[-1, :] = [10, 11, 12]

B = np.array([1, 2, 3])

det_A = np.linalg.det(A)

if det_A != 0:
    print("The matrix A is invertible.")
    
    inv_A = np.linalg.inv(A)
    
    X = np.dot(inv_A, B)
    
    print("Solution to the system of linear equations (X):")
    print(X)
else:
    print("The matrix A is not invertible.")

The matrix A is not invertible.


In [7]:
import numpy as np

C = np.random.randint(1, 21, size=(4, 4))
print("Matrix C:")
print(C)

rank_C = np.linalg.matrix_rank(C)
print("\nRank of Matrix C:")
print(rank_C)

submatrix_C = C[:2, -2:]
print("\nSubmatrix of C (first 2 rows and last 2 columns):")
print(submatrix_C)

frobenius_norm_C = np.linalg.norm(C)
print("\nFrobenius Norm of Matrix C:")
print(frobenius_norm_C)

Matrix C:
[[15  2 18 12]
 [ 9 19 11 13]
 [12 11 10  2]
 [16 11 17  4]]

Rank of Matrix C:
4

Submatrix of C (first 2 rows and last 2 columns):
[[18 12]
 [11 13]]

Frobenius Norm of Matrix C:
49.79959839195493


In [8]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A[-1, :] = [10, 11, 12]

C = np.random.randint(1, 21, size=(4, 4))
print("Matrix C:")
print(C)

C = C[:3, :3]

if A.shape[1] == C.shape[0]:
    print("\nMatrix multiplication is valid.")
    result = np.dot(A, C)
    print("Result of Matrix Multiplication:")
    print(result)
else:
    print("\nMatrix multiplication is not valid. Reshaping C to make it compatible with A.")
    C = C.T  
    print("Reshaped Matrix C:")
    print(C)
    result = np.dot(A, C)
    print("Result of Matrix Multiplication:")
    print(result)

Matrix C:
[[18 16  1 19]
 [ 7 20 17  4]
 [ 9 17  5 14]
 [17  8  9 14]]

Matrix multiplication is valid.
Result of Matrix Multiplication:
[[ 59 107  50]
 [161 266 119]
 [365 584 257]]


In [10]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Create a dataset as a 5 × 5 matrix D
D = np.array([[3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10], 
              [1, 3, 5, 7, 9], 
              [4, 6, 8, 10, 12], 
              [5, 7, 9, 11, 13]])

# Standardize D column-wise (mean = 0, variance = 1)
scaler = StandardScaler()
D_std = scaler.fit_transform(D)

# Compute the covariance matrix of D
cov_matrix = np.cov(D_std.T)

# Perform Principal Component Analysis (PCA)
pca = PCA(n_components=2)
D_pca = pca.fit_transform(D_std)

# Find the eigenvalues and eigenvectors of the covariance matrix
eigenvalues = pca.explained_variance_ratio_
eigenvectors = pca.components_

# Output results
print("Standardized Matrix D:")
print(D_std)
print("\nCovariance Matrix of D:")
print(cov_matrix)
print("\nEigenvalues (Variance explained by each principal component):")
print(eigenvalues)
print("\nEigenvectors (Principal components):")
print(eigenvectors)
print("\nMatrix D reduced to 2 principal components:")
print(D_pca)

Standardized Matrix D:
[[ 0.          0.          0.          0.          0.        ]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [-1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [ 0.70710678  0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356]]

Covariance Matrix of D:
[[1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]]

Eigenvalues (Variance explained by each principal component):
[1.00000000e+00 3.94430453e-33]

Eigenvectors (Principal components):
[[ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 0.89442719 -0.2236068  -0.2236068  -0.2236068  -0.2236068 ]]

Matrix D reduced to 2 principal components:
[[-0.00000000e+00 -3.14018492e-16]
 [-1.58113883e+00 -3.48630560e-32]
 [-3.16227766e+00  0.00000000e+00]
 [ 1.58113883e+00  0.00000000e+00]
 [ 3.16227766e+00  0.00000000e+00]]
